# Generated by Django 5.2.3 on 2025-07-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userlog_options_alter_userlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='assigned_auditor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_missions', to=settings.AUTH_USER_MODEL, verbose_name='Auditeur assigné'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.CharField(blank=True, max_length=200, verbose_name='Client'),
        ),
    ]
