# Generated by Django 5.2.2 on 2025-06-11 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapprochementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_session', models.CharField(max_length=255, verbose_name='Nom de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('nb_employes_rh', models.PositiveIntegerField(default=0, help_text='Employés dans la liste RH')),
                ('nb_employes_payes', models.PositiveIntegerField(default=0, help_text='Employés payés')),
                ('nb_matches_parfaits', models.PositiveIntegerField(default=0, help_text='Rapprochements parfaits')),
                ('nb_matches_partiels', models.PositiveIntegerField(default=0, help_text='Rapprochements partiels')),
                ('nb_non_payes', models.PositiveIntegerField(default=0, help_text='Employés RH non payés')),
                ('nb_non_declares', models.PositiveIntegerField(default=0, help_text='Payés non déclarés en RH')),
                ('nb_doublons', models.PositiveIntegerField(default=0, help_text='Paies multiples détectées')),
                ('logs_traitement', models.JSONField(default=list, help_text='Logs du traitement')),
                ('erreurs', models.TextField(blank=True, help_text='Erreurs rencontrées')),
                ('fichier_liste_personnel', models.ForeignKey(help_text='Fichier RH avec les employés qui doivent être payés', on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements_comme_liste', to='uploads.fichierimporte', verbose_name='Liste du personnel à payer')),
                ('fichier_paie', models.ForeignKey(help_text='Fichier avec les employés effectivement payés', on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements_comme_paie', to='uploads.fichierimporte', verbose_name='Fichier de paie')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements', to='accounts.mission', verbose_name='Mission')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Session de rapprochement',
                'verbose_name_plural': 'Sessions de rapprochement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ResultatRapprochement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_match', models.CharField(choices=[('parfait', 'Match parfait'), ('partiel', 'Match partiel'), ('non_paye', 'Non payé'), ('non_declare', 'Non déclaré'), ('doublon', 'Doublon détecté')], max_length=20)),
                ('critere_match', models.CharField(choices=[('matricule', 'Matricule'), ('nom_prenom_ddn', 'Nom + Prénom + Date naissance'), ('rib', 'RIB'), ('aucun', 'Aucun')], default='aucun', max_length=20)),
                ('score_confiance', models.FloatField(default=0.0, help_text='Score de 0 à 100')),
                ('matricule_rh', models.CharField(blank=True, max_length=50)),
                ('nom_rh', models.CharField(blank=True, max_length=100)),
                ('prenom_rh', models.CharField(blank=True, max_length=100)),
                ('poste_rh', models.CharField(blank=True, max_length=100)),
                ('rib_rh', models.CharField(blank=True, max_length=100)),
                ('salaire_prevu_rh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('matricule_paie', models.CharField(blank=True, max_length=50)),
                ('nom_paie', models.CharField(blank=True, max_length=100)),
                ('prenom_paie', models.CharField(blank=True, max_length=100)),
                ('rib_paie', models.CharField(blank=True, max_length=100)),
                ('salaire_brut_paie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_total_paie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ecart_salaire', models.DecimalField(blank=True, decimal_places=2, help_text='Différence entre salaire prévu et payé', max_digits=12, null=True)),
                ('commentaires', models.TextField(blank=True, help_text='Commentaires sur le rapprochement')),
                ('ligne_rh', models.PositiveIntegerField(blank=True, help_text='Numéro de ligne dans le fichier RH', null=True)),
                ('ligne_paie', models.PositiveIntegerField(blank=True, help_text='Numéro de ligne dans le fichier paie', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='reconciliation.rapprochementsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Résultat de rapprochement',
                'verbose_name_plural': 'Résultats de rapprochement',
                'ordering': ['type_match', 'nom_rh', 'nom_paie'],
            },
        ),
        migrations.CreateModel(
            name='RegleValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_regle', models.CharField(choices=[('matricule_obligatoire', 'Matricule obligatoire'), ('tolerance_salaire', 'Tolérance écart salaire'), ('format_rib', 'Validation format RIB'), ('doublon_rib', 'Détection doublons RIB')], max_length=50)),
                ('nom_regle', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('description', models.TextField(blank=True)),
                ('valeur_numerique', models.FloatField(blank=True, help_text='Valeur numérique si applicable', null=True)),
                ('valeur_texte', models.CharField(blank=True, help_text='Valeur texte si applicable', max_length=500)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_validation', to='accounts.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Règle de validation',
                'verbose_name_plural': 'Règles de validation',
                'unique_together': {('mission', 'type_regle')},
            },
        ),
    ]
