# Generated by Django 5.2.2 on 2025-06-12 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reconciliation', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_isolation_forest', models.FloatField(default=0.75, help_text='Seuil pour considérer une observation comme anomalie (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('score_minimum_classification', models.FloatField(default=0.6, help_text='Score minimum pour valider une classification MLP (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('utiliser_modele_global', models.BooleanField(default=True, help_text="Utiliser le modèle global ou permettre l'affinage par mission")),
                ('reentrainement_auto', models.BooleanField(default=False, help_text='Réentraînement automatique avec les corrections utilisateur')),
                ('nb_anomalies_max_dashboard', models.PositiveIntegerField(default=50, help_text="Nombre maximum d'anomalies à afficher sur le dashboard")),
                ('afficher_explications', models.BooleanField(default=True, help_text='Afficher les explications des décisions IA')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramétrage IA',
                'verbose_name_plural': 'Paramétrage IA',
            },
        ),
        migrations.CreateModel(
            name='SessionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_session', models.CharField(max_length=255, verbose_name='Nom de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'Traitement en cours'), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('seuil_if_utilise', models.FloatField(blank=True, null=True)),
                ('seuil_mlp_utilise', models.FloatField(blank=True, null=True)),
                ('modele_utilise', models.CharField(blank=True, help_text='Nom du modèle utilisé (global ou spécifique mission)', max_length=100)),
                ('nb_lignes_analysees', models.PositiveIntegerField(default=0)),
                ('nb_anomalies_detectees', models.PositiveIntegerField(default=0)),
                ('nb_salaires_anormaux', models.PositiveIntegerField(default=0)),
                ('nb_employes_fantomes', models.PositiveIntegerField(default=0)),
                ('nb_primes_anormales', models.PositiveIntegerField(default=0)),
                ('nb_heures_excessives', models.PositiveIntegerField(default=0)),
                ('nb_rib_dupliques', models.PositiveIntegerField(default=0)),
                ('nb_aucune_anomalie', models.PositiveIntegerField(default=0)),
                ('duree_traitement_secondes', models.FloatField(blank=True, null=True)),
                ('logs_traitement', models.JSONField(default=list, help_text='Logs détaillés du traitement')),
                ('erreurs', models.TextField(blank=True, help_text='Erreurs rencontrées')),
                ('fichier_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits_comme_source', to='uploads.fichierimporte', verbose_name='Fichier de paie analysé')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_audit', to='accounts.mission', verbose_name='Mission')),
                ('session_rapprochement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_generes', to='reconciliation.rapprochementsession', verbose_name='Session de rapprochement associée')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits_crees', to=settings.AUTH_USER_MODEL, verbose_name='Lancé par')),
            ],
            options={
                'verbose_name': "Session d'audit IA",
                'verbose_name_plural': "Sessions d'audit IA",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ResultatAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne_fichier', models.PositiveIntegerField(help_text='Numéro de ligne dans le fichier')),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('rib', models.CharField(blank=True, max_length=100)),
                ('salaire_brut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('heures_travaillees', models.FloatField(blank=True, null=True)),
                ('montant_primes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_anomalie', models.BooleanField(default=False, verbose_name='Anomalie détectée')),
                ('score_anomalie_if', models.FloatField(blank=True, help_text='Score Isolation Forest (0-1, plus proche de 1 = plus anormal)', null=True)),
                ('type_anomalie', models.CharField(choices=[('salaire_anormal', 'Salaire anormal'), ('ghost_employee', 'Employé fantôme'), ('prime_anormale', 'Prime anormale'), ('heures_excessives', 'Heures excessives'), ('duplicate_rib', 'RIB dupliqué'), ('aucune', 'Aucune anomalie')], default='aucune', max_length=20)),
                ('score_classification_mlp', models.FloatField(blank=True, help_text='Score de confiance MLP pour la classification (0-1)', null=True)),
                ('niveau_risque', models.CharField(choices=[('faible', 'Risque faible'), ('moyen', 'Risque moyen'), ('eleve', 'Risque élevé'), ('critique', 'Risque critique')], default='faible', max_length=20)),
                ('explication_if', models.TextField(blank=True, help_text='Explication de la détection Isolation Forest')),
                ('explication_mlp', models.TextField(blank=True, help_text='Explication de la classification MLP')),
                ('recommandation_auto', models.TextField(blank=True, help_text='Recommandation générée automatiquement')),
                ('valide_par_humain', models.BooleanField(default=False, help_text='Résultat validé par un utilisateur')),
                ('est_fausse_alerte', models.BooleanField(default=False, help_text='Marqué comme fausse alerte par utilisateur')),
                ('commentaire_utilisateur', models.TextField(blank=True, help_text='Commentaire de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='auditengine.sessionaudit', verbose_name="Session d'audit")),
            ],
            options={
                'verbose_name': "Résultat d'audit",
                'verbose_name_plural': "Résultats d'audit",
                'ordering': ['-score_anomalie_if', '-score_classification_mlp'],
            },
        ),
        migrations.CreateModel(
            name='ModeleIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('type_modele', models.CharField(choices=[('isolation_forest', 'Isolation Forest'), ('mlp_classifier', 'MLP Classifier')], max_length=20)),
                ('scope', models.CharField(choices=[('global', 'Modèle global'), ('mission', 'Modèle spécifique mission')], default='global', max_length=10)),
                ('fichier_modele', models.CharField(help_text='Chemin vers le fichier .pkl du modèle', max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('nb_echantillons_entrainement', models.PositiveIntegerField(blank=True, null=True)),
                ('date_entrainement', models.DateTimeField(blank=True, null=True)),
                ('entrainement_base_sur', models.TextField(blank=True, help_text="Sources de données utilisées pour l'entraînement")),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_crees', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, help_text='Mission spécifique (null pour modèle global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeles_ia', to='accounts.mission')),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
                'ordering': ['-date_creation'],
                'unique_together': {('type_modele', 'scope', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='CorrectionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_correction', models.CharField(choices=[('fausse_alerte', 'Fausse alerte'), ('vraie_anomalie', 'Vraie anomalie non détectée'), ('reclassification', 'Reclassification du type'), ('validation', 'Validation positive')], max_length=20)),
                ('ancien_est_anomalie', models.BooleanField(blank=True, null=True)),
                ('ancien_type_anomalie', models.CharField(blank=True, max_length=20)),
                ('ancien_niveau_risque', models.CharField(blank=True, max_length=20)),
                ('nouveau_est_anomalie', models.BooleanField(blank=True, null=True)),
                ('nouveau_type_anomalie', models.CharField(blank=True, max_length=20)),
                ('nouveau_niveau_risque', models.CharField(blank=True, max_length=20)),
                ('justification', models.TextField(help_text="Explication de la correction pour l'apprentissage")),
                ('confiance_utilisateur', models.PositiveIntegerField(default=5, help_text="Niveau de confiance de l'utilisateur (1-10)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_correction', models.DateTimeField(auto_now_add=True)),
                ('utilisee_pour_entrainement', models.BooleanField(default=False, help_text='Cette correction a été utilisée pour réentraîner le modèle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_apportees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('resultat_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='auditengine.resultataudit', verbose_name='Résultat corrigé')),
            ],
            options={
                'verbose_name': 'Correction utilisateur',
                'verbose_name_plural': 'Corrections utilisateurs',
                'ordering': ['-date_correction'],
                'unique_together': {('resultat_audit', 'utilisateur')},
            },
        ),
        migrations.AddIndex(
            model_name='resultataudit',
            index=models.Index(fields=['est_anomalie', 'type_anomalie'], name='auditengine_est_ano_cca23d_idx'),
        ),
        migrations.AddIndex(
            model_name='resultataudit',
            index=models.Index(fields=['session', 'niveau_risque'], name='auditengine_session_f6abfa_idx'),
        ),
    ]
