# Generated by Django 5.2.2 on 2025-06-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditengine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrageia',
            name='nb_anomalies_max_dashboard',
        ),
        migrations.AddField(
            model_name='parametrageia',
            name='nb_anomalies_max_tableau_de_bord',
            field=models.PositiveIntegerField(default=50, help_text="Nombre maximum d'anomalies à afficher sur le tableau de bord"),
        ),
    ]
