# Generated by Django 5.2.2 on 2025-06-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditengine', '0002_remove_parametrageia_nb_anomalies_max_dashboard_and_more'),
    ]

    operations = [
    ]
