# Generated by Django 5.2.3 on 2025-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditengine', '0003_remove_nb_anomalies_max_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultataudit',
            name='type_anomalie',
            field=models.CharField(choices=[('salaire_anormal', 'Salaire anormal'), ('ghost_employee', 'Employé fantôme'), ('prime_anormale', 'Prime anormale'), ('heures_excessives', 'Heures excessives'), ('duplicate_rib', 'RIB dupliqué'), ('anomalie_non_classifiee', 'Anomalie non classifiée'), ('aucune', 'Aucune anomalie')], default='aucune', max_length=25),
        ),
    ]
