# Generated by Django 5.2.3 on 2025-08-21 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditengine', '0004_alter_resultataudit_type_anomalie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrageia',
            name='score_minimum_classification',
            field=models.FloatField(default=0.8, help_text='Score minimum pour valider une classification MLP (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.CreateModel(
            name='TacheAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(choices=[('salaire_anormal', 'Salaire anormal'), ('ghost_employee', 'Employé fantôme'), ('prime_anormale', 'Prime anormale'), ('heures_excessives', 'Heures excessives'), ('duplicate_rib', 'RIB dupliqué'), ('anomalie_non_classifiee', 'Anomalie non classifiée'), ('aucune', 'Aucune anomalie')], max_length=50, verbose_name="Type d'anomalie")),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la tâche')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('action_requise', models.TextField(verbose_name='Action à effectuer')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('elevee', 'Élevée'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('a_creer', 'À créer'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_creer', max_length=20)),
                ('delai', models.CharField(max_length=50, verbose_name='Délai recommandé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('nb_cas_concernes', models.PositiveIntegerField(default=0, verbose_name='Nombre de cas concernés')),
                ('impact_financier_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impact financier estimé (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de suivi')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('session_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_actions', to='auditengine.sessionaudit', verbose_name="Session d'audit")),
            ],
            options={
                'verbose_name': "Tâche d'action",
                'verbose_name_plural': "Tâches d'action",
                'ordering': ['-priorite', '-date_creation'],
            },
        ),
    ]
