# Generated by Django 5.2.17 on 2026-09-14 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditengine', '0005_alter_parametrageia_score_minimum_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_session', 'Création de session'), ('start_analysis', 'Démarrage analyse'), ('complete_analysis', 'Analyse terminée'), ('view_results', 'Consultation résultats'), ('export_results', 'Export résultats'), ('view_anomaly', 'Consultation anomalie'), ('correct_anomaly', 'Correction anomalie'), ('validate_anomaly', 'Validation anomalie'), ('mark_false_alert', 'Marquage fausse alerte'), ('generate_recommendations', 'Génération recommandations'), ('view_recommendations', 'Consultation recommandations'), ('export_recommendations', 'Export recommandations'), ('create_task', 'Création tâche'), ('assign_task', 'Assignation tâche'), ('complete_task', 'Tâche terminée'), ('view_tasks', 'Consultation tâches'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('access_denied', 'Accès refusé'), ('error', 'Erreur système')], max_length=50, verbose_name='Action')),
                ('feature', models.CharField(max_length=50, verbose_name='Fonctionnalité')),
                ('target', models.CharField(max_length=50, verbose_name='Cible')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID Ressource')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Type Ressource')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('old_value', models.TextField(blank=True, verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID Session')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Sévérité')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Suspect')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='auditengine_user_id_dfb497_idx'), models.Index(fields=['action', 'timestamp'], name='auditengine_action_cdb38c_idx'), models.Index(fields=['resource_type', 'resource_id'], name='auditengine_resourc_08631c_idx'), models.Index(fields=['severity', 'timestamp'], name='auditengine_severit_b89387_idx')],
            },
        ),
    ]
