# Generated by Django 5.2.17 on 2026-09-14 18:50

from django.db import migrations, models


def backfill_type_anomalie_predit_ia(apps, schema_editor):
    """Best-effort pour les lignes existantes : pour les résultats jamais
    corrigés, type_anomalie EST encore la prédiction brute de l'IA, donc la
    copie est exacte. Pour les résultats déjà corrigés, la prédiction
    d'origine n'a jamais été conservée ailleurs — impossible à reconstituer
    rétroactivement — donc on reporte la valeur actuelle en dernier recours
    plutôt que de laisser 'aucune' partout, qui serait faux pour toutes les
    lignes en anomalie.
    """
    ResultatAudit = apps.get_model('auditengine', 'ResultatAudit')
    ResultatAudit.objects.update(type_anomalie_predit_ia=models.F('type_anomalie'))


class Migration(migrations.Migration):

    dependencies = [
        ('auditengine', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultataudit',
            name='type_anomalie_predit_ia',
            field=models.CharField(choices=[('salaire_anormal', 'Salaire anormal'), ('ghost_employee', 'Employé fantôme'), ('prime_anormale', 'Prime anormale'), ('heures_excessives', 'Heures excessives'), ('duplicate_rib', 'RIB dupliqué'), ('anomalie_non_classifiee', 'Anomalie non classifiée'), ('aucune', 'Aucune anomalie')], default='aucune', editable=False, help_text="Prédiction brute du MLP au moment de l'analyse, figée définitivement. Sert de référence pour évaluer le modèle indépendamment des corrections humaines appliquées ensuite à 'type_anomalie'.", max_length=25),
        ),
        migrations.RunPython(backfill_type_anomalie_predit_ia, migrations.RunPython.noop),
    ]
