# Generated by Django 5.2.2 on 2025-06-10 14:48

import django.db.models.deletion
import uploads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierImporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('paie', 'Fichier de paie'), ('liste_personnel', 'Liste du personnel à payer'), ('grille', 'Grille salariale'), ('convention', 'Convention collective'), ('procedure', 'Procédure interne')], max_length=30, verbose_name='Type de fichier')),
                ('fichier', models.FileField(upload_to=uploads.models.upload_to_mission_folder, validators=[uploads.models.validate_file_extension, uploads.models.validate_file_size], verbose_name='Fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom original')),
                ('taille_fichier', models.PositiveIntegerField(help_text='Taille en bytes')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('processed', 'Traité'), ('error', 'Erreur'), ('approved', 'Approuvé')], default='pending', max_length=20, verbose_name='Statut')),
                ('nb_lignes', models.PositiveIntegerField(blank=True, help_text='Nombre de lignes détectées', null=True)),
                ('colonnes_detectees', models.JSONField(default=list, help_text='Liste des colonnes détectées')),
                ('erreurs_processing', models.TextField(blank=True, help_text='Erreurs lors du traitement')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Fichier validé')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('fichier_precedent', models.ForeignKey(blank=True, help_text='Version précédente de ce fichier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.fichierimporte', verbose_name='Fichier précédent')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='accounts.mission', verbose_name='Mission')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_importes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Fichier importé',
                'verbose_name_plural': 'Fichiers importés',
                'ordering': ['-date_import'],
                'unique_together': {('mission', 'type_fichier', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PreviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonnes', models.JSONField(help_text='Liste des colonnes du fichier', verbose_name='Colonnes')),
                ('donnees_echantillon', models.JSONField(help_text='Premières lignes pour prévisualisation', verbose_name='Données échantillon')),
                ('nb_total_lignes', models.PositiveIntegerField(verbose_name='Nombre total de lignes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('fichier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='uploads.fichierimporte', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Aperçu des données',
                'verbose_name_plural': 'Aperçus des données',
            },
        ),
        migrations.CreateModel(
            name='MappingColonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonne_fichier', models.CharField(max_length=100, verbose_name='Colonne du fichier')),
                ('colonne_attendue', models.CharField(max_length=100, verbose_name='Colonne attendue')),
                ('est_confirme', models.BooleanField(default=False, verbose_name='Mapping confirmé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='uploads.fichierimporte', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Mapping de colonne',
                'verbose_name_plural': 'Mappings de colonnes',
                'unique_together': {('fichier', 'colonne_attendue')},
            },
        ),
    ]
