# Generated by Django 5.2.2 on 2025-06-24 02:15

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierimporte',
            name='fichier',
            field=models.FileField(upload_to=uploads.models.upload_to_mission_folder, validators=[uploads.models.validate_file_extension, uploads.models.validate_file_size, uploads.models.validate_file_content], verbose_name='Fichier'),
        ),
    ]
