# Generated by Django 5.2.2 on 2025-06-13 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userlog_options_alter_userlog_user'),
        ('auditengine', '0001_initial'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_recommandation', models.CharField(help_text='Code unique auto-généré (ex: REC-2024-001)', max_length=20, unique=True, verbose_name='Code recommandation')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('type_recommandation', models.CharField(choices=[('correctif', 'Action corrective'), ('preventif', 'Action préventive'), ('amelioration', 'Amélioration processus'), ('formation', 'Formation/Sensibilisation'), ('controle', 'Renforcement contrôles'), ('organisationnel', 'Changement organisationnel'), ('technique', 'Amélioration technique')], max_length=20, verbose_name='Type')),
                ('priorite', models.CharField(choices=[('critique', '🔴 Critique'), ('haute', '🟠 Haute'), ('moyenne', '🟡 Moyenne'), ('basse', '🟢 Basse')], max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente validation'), ('approved', 'Approuvée'), ('assigned', 'Assignée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('rejected', 'Rejetée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=15, verbose_name='Statut')),
                ('source', models.CharField(choices=[('auto_audit', 'Génération automatique - Audit IA'), ('auto_reconciliation', 'Génération automatique - Rapprochement'), ('auto_pattern', 'Génération automatique - Pattern'), ('manual_auditor', 'Saisie manuelle - Auditeur'), ('manual_manager', 'Saisie manuelle - Manager'), ('manual_rh', 'Saisie manuelle - RH')], max_length=25, verbose_name='Source de création')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('duree_estimee_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (jours)')),
                ('pourcentage_avancement', models.PositiveIntegerField(default=0, help_text="Pourcentage d'avancement de 0 à 100", verbose_name='Avancement (%)')),
                ('impact_estime', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('fort', 'Fort'), ('critique', 'Critique')], default='moyen', max_length=10, verbose_name='Impact estimé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_assignation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation")),
                ('date_debut_reel', models.DateTimeField(blank=True, null=True, verbose_name='Date de début réel')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('efficacite_realisee', models.CharField(choices=[('non_evaluee', 'Non évaluée'), ('insuffisante', 'Insuffisante'), ('partielle', 'Partielle'), ('satisfaisante', 'Satisfaisante'), ('excellente', 'Excellente')], default='non_evaluee', max_length=20, verbose_name='Efficacité réalisée')),
                ('commentaire_cloture', models.TextField(blank=True, verbose_name='Commentaire de clôture')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('donnees_contexte', models.JSONField(blank=True, default=dict, help_text='Données contextuelles JSON (scores IA, métriques, etc.)')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags pour catégorisation (ex: ['urgent', 'paie', 'formation'])")),
                ('anomalie_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='auditengine.resultataudit', verbose_name='Anomalie liée')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='accounts.mission', verbose_name='Mission')),
                ('session_audit_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='auditengine.sessionaudit', verbose_name="Session d'audit liée")),
                ('session_rapprochement_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='reconciliation.rapprochementsession', verbose_name='Session de rapprochement liée')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouvelle', 'Nouvelle recommandation'), ('assignation', 'Assignation'), ('echeance_proche', 'Échéance proche'), ('retard', 'Retard détecté'), ('validation_requise', 'Validation requise'), ('completion', 'Recommandation terminée')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('email_envoye', models.BooleanField(default=False)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recommandations', to=settings.AUTH_USER_MODEL)),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recommendations.recommandation')),
            ],
            options={
                'verbose_name': 'Notification recommandation',
                'verbose_name_plural': 'Notifications recommandations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_action', models.CharField(max_length=255, verbose_name="Nom de l'action")),
                ('description_action', models.TextField(verbose_name='Description détaillée')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="Ordre d'exécution")),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('duree_estimee_heures', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (heures)')),
                ('statut', models.CharField(choices=[('non_commencee', 'Non commencée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('bloquee', 'Bloquée'), ('annulee', 'Annulée')], default='non_commencee', max_length=15, verbose_name='Statut')),
                ('pourcentage_completion', models.PositiveIntegerField(default=0, verbose_name='Completion (%)')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('contributeurs', models.ManyToManyField(blank=True, related_name='actions_contributeur', to=settings.AUTH_USER_MODEL, verbose_name='Contributeurs')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='recommendations.recommandation', verbose_name='Recommandation')),
            ],
            options={
                'verbose_name': 'Action du plan',
                'verbose_name_plural': 'Actions du plan',
                'ordering': ['recommandation', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='SuiviAvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('assignation', 'Assignation'), ('debut_travaux', 'Début des travaux'), ('mise_a_jour', 'Mise à jour avancement'), ('commentaire', 'Ajout commentaire'), ('cloture', 'Clôture'), ('rouverture', 'Réouverture')], max_length=20, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('commentaire_utilisateur', models.TextField(blank=True, verbose_name='Commentaire utilisateur')),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('donnees_avant', models.JSONField(blank=True, default=dict, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, default=dict, verbose_name='Données après modification')),
                ('fichiers_joints', models.JSONField(blank=True, default=list, help_text='URLs des fichiers joints (preuves, captures, etc.)')),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='recommendations.recommandation', verbose_name='Recommandation')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Suivi d'avancement",
                'verbose_name_plural': "Suivis d'avancement",
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='KPIRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('nb_recommandations_creees', models.PositiveIntegerField(default=0)),
                ('nb_recommandations_terminees', models.PositiveIntegerField(default=0)),
                ('nb_recommandations_en_retard', models.PositiveIntegerField(default=0)),
                ('nb_correctifs', models.PositiveIntegerField(default=0)),
                ('nb_preventifs', models.PositiveIntegerField(default=0)),
                ('nb_ameliorations', models.PositiveIntegerField(default=0)),
                ('nb_formations', models.PositiveIntegerField(default=0)),
                ('nb_critiques', models.PositiveIntegerField(default=0)),
                ('nb_hautes', models.PositiveIntegerField(default=0)),
                ('nb_moyennes', models.PositiveIntegerField(default=0)),
                ('nb_basses', models.PositiveIntegerField(default=0)),
                ('duree_moyenne_traitement', models.FloatField(blank=True, help_text='Durée moyenne en jours', null=True)),
                ('taux_respect_echeances', models.FloatField(blank=True, help_text='Pourcentage (0-100)', null=True)),
                ('taux_completion', models.FloatField(blank=True, help_text='Pourcentage (0-100)', null=True)),
                ('score_efficacite_moyen', models.FloatField(blank=True, help_text="Score d'efficacité moyen (1-5)", null=True)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mission')),
            ],
            options={
                'verbose_name': 'KPI Recommandations',
                'verbose_name_plural': 'KPIs Recommandations',
                'ordering': ['-periode_fin'],
                'unique_together': {('mission', 'periode_debut', 'periode_fin')},
            },
        ),
        migrations.AddIndex(
            model_name='recommandation',
            index=models.Index(fields=['statut', 'priorite'], name='recommendat_statut_f1cb11_idx'),
        ),
        migrations.AddIndex(
            model_name='recommandation',
            index=models.Index(fields=['date_echeance'], name='recommendat_date_ec_048577_idx'),
        ),
        migrations.AddIndex(
            model_name='recommandation',
            index=models.Index(fields=['assigne_a', 'statut'], name='recommendat_assigne_b459a1_idx'),
        ),
    ]
